### ISSUE TITLE
Expose Migrondi as a library

### ISSUE THREAD

**Issue by AngelMunoz** [AngelMunoz/Migrondi#27]
**Is your feature request related to a problem? Please describe.**
Right now if you want to use Migrondi, you need to use the binary distribution to execute migrations ideally if you are a .NET user, you should be able to use Migrondi as a library

**Describe the solution you'd like**
Expose Migrondi core parts as a library with handy types (Func/Action for C#) (F# lambdas for F# users)

**Comment by AngelMunoz** [comment]
#28  has been merged and it includesthe facilities to use migrondi as a library, I will try to get a sample of a prototype using @JordanMarr 's SqlHydra.Query to re-take the fsx scripts it will also help me test the public API and see if it's actually usable

**Comment by JordanMarr** [comment]
Since the various query builders (select, insert, update and delete) all have different return types, I am in the process of adding a helper to transform a builder specific query spec to a `SqlKata.Query`, and another helper to turn a `SqlKata.Query` into an embedded SQL string. I think this would give you the flexibility you need for creating a clean list of migrations.

This is what I have so far.

![image](https://user-images.githubusercontent.com/1030435/129396017-a7210ef8-c42a-461e-a40b-8b13313499fa.png)

**Comment by JordanMarr** [comment]
Maybe you could have helpers like `Migrondi.readSqlFile` to return a sql string and `Migrondi.importMigrationFolder` to return a list of script strings from a migration folder that could be included in the list of scripts alongside query expressions. 🤔 
Not sure if that would be useful... just brainstorming with a fried brain. 😄

**Comment by JordanMarr** [comment]
On second thought, I just noticed that my naive `toEmbeddedSql` fn would need to do a lot more work to properly embed different data types in a db provider agnostic way.
i.e. strings need to be wrapped with single or double quotes depending on provider, etc.

Browsing through the `SqlKata` issues repo, I don't see any built-in functionality to do this.
So I that it would need to be a list of `IDbCommand` objects instead since it can already output embedded commands.

And it's easy to convert manual SQL string to a command.

**Comment by JordanMarr** [comment]
On second thought, I just noticed that my naive `toEmbeddedSql` fn would need to do a lot more work to properly embed different data types in a db provider agnostic way: strings need to be wrapped with single or double quotes depending on provider, etc.
Browsing through the SqlKata issues repo, I don't see any built-in functionality to do this.

So I think your original idea of just getting a list of `SqlKata.Query` objects would be the best. You can easily convert a `SqlKata.Query` object into command on your side.

Here's the updated version with some sample inserts included:

![image](https://user-images.githubusercontent.com/1030435/129401167-c0e1ab5e-4497-40fe-b3e9-99c70a54a9d6.png)

**Comment by AngelMunoz** [comment]
Yeah looks like the last one might do the trick, I'm also wary that this is going to run inside a fsx script so not sure how that will turn out specially if you have "#r" usings at the top performance might not be that great

**Comment by JordanMarr** [comment]
Since migrations would probably be run as part of a CI build, I can't imagine that a few seconds here or there would be that big of deal. Or do you think it would be longer than that?

But if performance is a concern, you could create a separate Migrondi package that would allow running it as its own executable.

Pros:  
- it would be easy to add a migration fsproj with migration "scripts-as-code"
- this package could share some of the existing code used by your dotnet tool
Cons: 
- would be a separate package to create

For some of my projects I use a FAKE build .fsx, but recently I have begun skipping using the FAKE dotnet tool and have instead been creating a FAKE build console .fsproj.  For some reason this seems easier to me because I can just pull it into my project via NuGet as opposed to mucking around with the dotnet command line tools.

**Comment by JordanMarr** [comment]
FYI, I just pushed [v0.200.1](https://www.nuget.org/packages/SqlHydra.Query/0.200.1) with the `Kata.ToQuery` helpers.

**Comment by JordanMarr** [comment]
More thoughts on creating a `list` of migrations-as-code... 
I can imagine you creating a series of "adapter" functions that transform the various inputs to some sort of a `MigrationScript` spec.
For example:
```F#
    let seedErrorsTable: SqlKata.Query list = 
        [ 
            for record in sampleErrors do
                insert {
                    into table<dbo.ErrorLog>
                    entity record
                }
                |> Kata.ToQuery 
            
            update {
                for e in table<dbo.ErrorLog> do
                set e.ErrorMessage "Unauthorized"
                where (e.ErrorNumber = 401)
            }
            |> Kata.ToQuery

            update {
                for e in table<dbo.ErrorLog> do
                set e.ErrorMessage "Resource Not Found"
                where (e.ErrorNumber = 404)
            }
            |> Kata.ToQuery
        ]

    let doSomethingCmd = 
        new Microsoft.Data.SqlClient.SqlCommand("UPDATE...")

    let migration = 
        [
            yield! seedErrorsTable |> List.map Script.ofSqlKataQuery
            yield! IO.DirectoryInfo("./migrations/") |> Script.ofMigrationFolder
            IO.FileInfo("./scripts/do_stuff.sql") |> Script.ofSqlFile
            doSomethingCmd |> Script.ofCommand
        ]
```

**Comment by AngelMunoz** [comment]
I'm about to start with this actually, I think for the moment I just want to be sure I can pull .fsx scripts just like I used to do on the old branch, I'll get the queries and build a command to execute them, very very close to what you have there, I'm not sure if the Kata.ToQuery is needed yet, but I do appreciate the effort!
we could actually use that to create an "eject" kind of thing where you can emit all of the migrations in standard SQL (or even transform them between languages) and use the default migrondi mechanisms

**Comment by JordanMarr** [comment]
TBH, I have used SSDT for my last few big projects with no migration, so I don't have enough experience using migrations to know if my suggestions make sense. So whatever you think is best, I defer to your judgement!

**Comment by AngelMunoz** [comment]
This is already part of the vnext preview on nuget, closing to clean up for the next batch of stuff 
there's a sample of this in the samples/script.fsx file
